### ISSUE TITLE
训练是损失报错

### ISSUE THREAD

**Issue by QinWinner** [Tianxiaomo/pytorch-YOLOv4#107]
请教一下为什么我会出现这样的一个问题。我已经仔细检查了我的配置文件，并没有错误。
Please ask me why I have such a problem. I have carefully examined my profile and made no mistake

/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THCUNN/BCECriterion.cu:74: Acctype bce_functor_weights<Dtype, Acctyuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::device_reference<floattype, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [put <= 1.` failed.
Epoch 1/300:  48%|▍| 512/1074 [00:41<00:45, 12.26i
Traceback (most recent call last):
  File "train.py", line 444, in <module>
    device=device, )
  File "train.py", line 320, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "/home/qinjian/anaconda3/envs/cell/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 221, in forward
    weight=tgt_scale * tgt_scale, size_average=False)
  File "/home/qinjian/anaconda3/envs/cell/lib/python3.6/site-packages/torch/nn/functional.py", line 2077, in binary_cross_en
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered

**Comment by QinWinner** [comment]
我减少了我批次大小成功解决了这个问题。
I reduced my batch size successfully solved this problem

**Comment by Tianxiaomo** [comment]
可以检查一下pytorch的版本，目前是否还存在这个问题

**Comment by RocketFlash** [comment]
I have the same error. @QinWinner have you solved it?

**Comment by QinWinner** [comment]
@RocketFlash  Changing the version of pytorch to 1.4.0 solves this problem.

**Comment by RocketFlash** [comment]
My pytorch version is also 1.4.0 :( I get this error when iteration number == batch size

**Comment by QinWinner** [comment]
@RocketFlash Sorry, I don't know how to fix this. Maybe you can see if the label data is regulated.

**Comment by suntxy** [comment]
just got same error in custom data, really weired.

**Comment by jjw12345** [comment]
I have the same error. Have you solved it?

**Comment by Freder-chen** [comment]
> My pytorch version is also 1.4.0 :( I get this error when iteration number == batch size

I get `RuntimeError: reduce failed to synchronize: cudaErrorAssert: device-side assert triggered` when iteration number == batch size. Have you fix it now? :) By the way, torch version is 1.4.0.

**Comment by chunish** [comment]
I encountered the same issue, and it did not work even replacing the binary_cross_entropy whith binary_cross_entropy_with_logits. but, finally, I checked my training dataset, found it existed some error items: bbox x1=x2, or y1=y2, after I removed these items and retrain, the bug was disappeared.
