### ISSUE TITLE
 shape '[1, 17328]' is invalid for input of size 5776

### ISSUE THREAD

**Issue by hx358031364** [Tianxiaomo/pytorch-YOLOv4#111]
按照Use_yolov4_to_train_your_own_data.md
用python model.py 3 weight/Yolov4_epoch166_coins.pth data/coin2.jpg data/coins.names报错，训练完需要再转换下模型吗？

**Comment by mon28** [comment]
Stuck with the same issue while training on custom dataset. filter before yolo layers is already (5+n_classes)*3

```
Traceback (most recent call last):
  File "train.py", line 446, in <module>
    device=device, )
  File "train.py", line 322, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "/data/mtare/pytorch-YOLOv4/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 197, in forward
    output = output.view(batchsize, self.n_anchors, n_ch, fsize, fsize)
RuntimeError: shape '[4, 3, 10, 52, 52]' is invalid for input of size 2758080
```

**Comment by mon28** [comment]
In train.py, change the following line in the main function at the end from: 

`model =Yolov4(cfg.pretrained, n_classes=cfg.classes)`

to

`model = Yolov4(Cfg.pretrained,n_classes=Cfg.classes)`

**Comment by hx358031364** [comment]
> In train.py, change the following line in the main function at the end from:
> 
> `model = Yolov4(cfg.pretrained, n_classes=cfg.classes)`
> 
> to
> 
> `model = Yolov4(Cfg.pretrained,n_classes=Cfg.classes)`

如果改成Cfg，那在执行python train.py -l 0.001 -g 4 -pretrained ./yolov4.conv.137.pth -classes 3 -dir /home/OCR/coins 这个命令的时候输入参数不就没用了么，调用的是配置文件参数了，main function 调用cfg = get_args(**Cfg)

def get_args(**kwargs):
    cfg = kwargs
    parser = argparse.ArgumentParser(description='Train the Model on images and target masks',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    # parser.add_argument('-b', '--batch-size', metavar='B', type=int, nargs='?', default=2,
    #                     help='Batch size', dest='batchsize')
    parser.add_argument('-l', '--learning-rate', metavar='LR', type=float, nargs='?', default=0.001,
                        help='Learning rate', dest='learning_rate')
    parser.add_argument('-f', '--load', dest='load', type=str, default=None,
                        help='Load checkpoints from a .pth file')
    parser.add_argument('-g', '--gpu', metavar='G', type=str, default='-1',
                        help='GPU', dest='gpu')
    parser.add_argument('-dir', '--data-dir', type=str, default=None,
                        help='dataset dir', dest='dataset_dir')
    parser.add_argument('-pretrained',type=str,default=None,help='pretrained yolov4.conv.137')
    parser.add_argument('-classes',type=int,default=80,help='dataset classes')
    parser.add_argument('-train_label_path',dest='train_label',type=str,default='train.txt',help="train label path")
    args = vars(parser.parse_args())

    for k in args.keys():
        cfg[k] = args.get(k)
    return edict(cfg)

**Comment by mon28** [comment]
Yes, hence either ensure to pass these parameters as arguments or change it Cfg if you are setting them in the cfg.py file. But if you skip them as arguments and want ti use the value from cfg.py, it wont automatically get picked up.

**Comment by hx358031364** [comment]
> Yes, hence either ensure to pass these parameters as arguments or change it Cfg if you are setting them in the cfg.py file. But if you skip them as arguments and want ti use the value from cfg.py, it wont automatically get picked up.

更改了使用Cfg的方式，但是错误还是一样

**Comment by lyhshang** [comment]
Yolov4Head类有个bug，
`
self.yolo1 = YoloLayer(..., num_classes=80,...)  
`
这里把类别写死了，把3个YoloLayer的参数num_classes改成你要的类数量，比如num_classes=3

**Comment by hx358031364** [comment]
> Yolov4Head类有个bug，
> `self.yolo1 = YoloLayer(..., num_classes=80,...) `
> 这里把类别写死了，把3个YoloLayer的参数num_classes改成你要的类数量，比如num_classes=3

好的，谢谢，改完后可以预测了
