### ISSUE TITLE
demo_trt调用转换好的tensorrt模型出错

### ISSUE THREAD

**Issue by tosonw** [Tianxiaomo/pytorch-YOLOv4#114]
您好，我在使用demo_trt调用转换好的engine时报错：
Traceback (most recent call last):
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/toson/softs/pycharm-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_ianxiaomo_20200614版/demo_trt.py", line 242, in <module>
    main(engine_path, image_path, image_size)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_ianxiaomo_20200614版/demo_trt.py", line 116, in main
    with get_engine(engine_path) as engine, engine.create_execution_context() as context:
AttributeError: __enter__
查看原因实在初始化读取engine文件时为空，with get_engine(engine_path) as engine 为空，单独测试这个engine文件是正确的，这个engine文件是使用CAOWGG的TensorRT-YOLOV4的方式转换的，请问大佬，需要怎么调整才能使用？？

**Comment by ersheng-ai** [comment]
This engine was generated from another GitHub repository that is outside my support capacity.
You can pull the latest code from this repository and try to generate and run your engine following the README here.
