### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by xungeer29** [Tianxiaomo/pytorch-YOLOv4#147]
1. dataset.py 需要加上import torch
2. coco_eval.py 222行 ```assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
        'Results do not correspond to current coco set'``` 这里引发了异常
3. 多GPU训练时，`torch.load()` 均报错，加个判断是否使用多gpu更好

**Comment by wenh06** [comment]
第二个是说做evaluate的图片不在validation set里。会不会是`drop_last`引起的呢？我训练的时候没有遇到过。另外，你说的报错这句我看是在第266行。

**Comment by wenh06** [comment]
> 1. dataset.py 需要加上import torch
> 2. coco_eval.py 222行 `assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \ 'Results do not correspond to current coco set'` 这里引发了异常
> 3. 多GPU训练时，`torch.load()` 均报错，加个判断是否使用多gpu更好

第三个问题的话，是不是需要像`tool.tv_reference.train.py`里面的`main(args)`函数一样改写`train.py`里的函数呢？我没有用过多GPU训练，暂时还不知道。

**Comment by xungeer29** [comment]
> > 1. dataset.py 需要加上import torch
> > 2. coco_eval.py 222行 `assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \ 'Results do not correspond to current coco set'` 这里引发了异常
> > 3. 多GPU训练时，`torch.load()` 均报错，加个判断是否使用多gpu更好
> 
> 第三个问题的话，是不是需要像`tool.tv_reference.train.py`里面的`main(args)`函数一样改写`train.py`里的函数呢？我没有用过多GPU训练，暂时还不知道。

我是加载模型时加了GPU数量的判断
```
if torch.cuda.device_count() > 1:
    eval_model.load_state_dict(model.module.state_dict())
else:
     eval_model.load_state_dict(model.state_dict())
```
另外，行数是我写错了，另外错误是`getImgIds`引起的，我是将`target['image_id'] = torch.tensor([get_image_id(img_path)])`改为`target['image_id'] = torch.tensor([index])`，使用`index`当作imageid

**Comment by xungeer29** [comment]
@wenh06 你有训coco吗？我用单卡2080试了一下，bs=2, 608输入，显存占了7G不到，要12h/epoch，我看作者说是单卡训的，不知道他要训多长时间

**Comment by wenh06** [comment]
> @wenh06 你有训coco吗？我用单卡2080试了一下，bs=2, 608输入，显存占了7G不到，要12h/epoch，我看作者说是单卡训的，不知道他要训多长时间

没试呢。我搞完目标检测的小项目之后现在在搞别的，目前这个已经delay很久了。。。。有时间我去试一下。

**Comment by wenh06** [comment]
> > > 1. dataset.py 需要加上import torch
> > > 2. coco_eval.py 222行 `assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \ 'Results do not correspond to current coco set'` 这里引发了异常
> > > 3. 多GPU训练时，`torch.load()` 均报错，加个判断是否使用多gpu更好
> > 
> > 
> > 第三个问题的话，是不是需要像`tool.tv_reference.train.py`里面的`main(args)`函数一样改写`train.py`里的函数呢？我没有用过多GPU训练，暂时还不知道。
> 
> 我是加载模型时加了GPU数量的判断
> 
> ```
> if torch.cuda.device_count() > 1:
>     eval_model.load_state_dict(model.module.state_dict())
> else:
>      eval_model.load_state_dict(model.state_dict())
> ```
> 
> 另外，行数是我写错了，另外错误是`getImgIds`引起的，我是将`target['image_id'] = torch.tensor([get_image_id(img_path)])`改为`target['image_id'] = torch.tensor([index])`，使用`index`当作imageid

好的，谢谢。我加上了。

**Comment by lishouji** [comment]
有大佬遇到过这个错误么
Traceback (most recent call last):
  File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 627, in <module>
    device=device, )
  File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 371, in train
    for i, batch in enumerate(train_loader):
  File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/dataset.py", line 284, in __getitem__
    img_path = os.path.join(self.cfg.dataset_dir, img_path)
  File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by xungeer29** [comment]
> 有大佬遇到过这个错误么
> Traceback (most recent call last):
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 627, in
> device=device, )
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 371, in train
> for i, batch in enumerate(train_loader):
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in **next**
> data = self.dataset_fetcher.fetch(index) # may raise StopIteration
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/dataset.py", line 284, in **getitem**
> img_path = os.path.join(self.cfg.dataset_dir, img_path)
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/posixpath.py", line 80, in join
> a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
没遇到，你把self.cfg.dataset_dir, img_path 打印出来看看，估计是这两个参数为空了

**Comment by lishouji** [comment]
确实两个都打印不出来



---原始邮件---
发件人: "xungeer29"<notifications@github.com&gt;
发送时间: 2020年7月27日(周一) 上午9:21
收件人: "Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"lishouji"<519366390@qq.com&gt;;
主题: Re: [Tianxiaomo/pytorch-YOLOv4] 一些bug (#147)




  
有大佬遇到过这个错误么
 Traceback (most recent call last):
 File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 627, in
 device=device, )
 File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 371, in train
 for i, batch in enumerate(train_loader):
 File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in next
 data = self.dataset_fetcher.fetch(index) # may raise StopIteration
 File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/dataset.py", line 284, in getitem
 img_path = os.path.join(self.cfg.dataset_dir, img_path)
 File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/posixpath.py", line 80, in join
 a = os.fspath(a)
 TypeError: expected str, bytes or os.PathLike object, not NoneType
 没遇到，你把self.cfg.dataset_dir, img_path 打印出来看看，估计是这两个参数为空了

**Comment by doduythao** [comment]
> 有大佬遇到过这个错误么
> Traceback (most recent call last):
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 627, in
> device=device, )
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 371, in train
> for i, batch in enumerate(train_loader):
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in **next**
> data = self.dataset_fetcher.fetch(index) # may raise StopIteration
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/dataset.py", line 284, in **getitem**
> img_path = os.path.join(self.cfg.dataset_dir, img_path)
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/posixpath.py", line 80, in join
> a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

I had the same problem, you should -dir to/the/path/of/coco2017/image.

**Comment by Fee532** [comment]
> 有大佬遇到过这个错误么
> Traceback (most recent call last):
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 627, in
> device=device, )
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/train.py", line 371, in train
> for i, batch in enumerate(train_loader):
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in **next**
> data = self.dataset_fetcher.fetch(index) # may raise StopIteration
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lsj/PycharmProjects/pytorch-YOLOv4-master/dataset.py", line 284, in **getitem**
> img_path = os.path.join(self.cfg.dataset_dir, img_path)
> File "/home/lsj/anaconda3/envs/yolov4/lib/python3.7/posixpath.py", line 80, in join
> a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

看了代码是要将相对路径上base成为绝对路径，我的训练设置的图片路径是绝对的，导致base时空的。我把join那一行注释了

**Comment by TigerandRosa** [comment]
有大佬遇见过 训练了两三轮，AP AR 都是0的问题嘛?

**Comment by wenh06** [comment]
> 有大佬遇见过 训练了两三轮，AP AR 都是0的问题嘛?

有可能标签有问题？或者你开tensorboard看看tf events里面记录的那些图？

**Comment by duys3416** [comment]
> 

训练两三轮AP都是0问题有没有找到原因？我也遇到这个问题，用的coco2017数据集
