### ISSUE TITLE
训练一段时间后，程序就中断了

### ISSUE THREAD

**Issue by arthur1060** [Tianxiaomo/pytorch-YOLOv4#171]
Traceback (most recent call last):
  File "D:/PycharmProjects/pytorch-YOLOv4-master/train.py", line 630, in <module>
    device=device, )
  File "D:/PycharmProjects/pytorch-YOLOv4-master/train.py", line 372, in train
    for i, batch in enumerate(train_loader):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\anaconda3\lib\multiprocessing\synchronize.py", line 104, in __getstate__
    h = context.get_spawning_popen().duplicate_for_child(sl.handle)
  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 95, in duplicate_for_child
    return reduction.duplicate(handle, self.sentinel)
  File "D:\anaconda3\lib\multiprocessing\reduction.py", line 77, in duplicate
    0, inheritable, _winapi.DUPLICATE_SAME_ACCESS)
PermissionError: [WinError 5] 拒绝访问

**Comment by arthur1060** [comment]
文件访问权限问题，见  https://blog.csdn.net/weixin_43870646/article/details/90020874
