### ISSUE TITLE
AttributeError: 'list' object has no attribute 'cpu', why? How to solve it!

### ISSUE THREAD

**Issue by PALMJJ** [Tianxiaomo/pytorch-YOLOv4#178]
Traceback (most recent call last):
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 624, in <module>
    device=device, )
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 425, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "/home/hengyuli/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 490, in evaluate
    outputs = outputs.cpu().detach().numpy()
AttributeError: 'list' object has no attribute 'cpu'

**Comment by ParkJinHyeock** [comment]
Same issue here.. I looked into the outputs, It's a list of tensor. And there is a annotated code above that line. To execute this code outputs must be list of dictionary like targets. I think code that convert tensor to dictionary needed...

**Comment by architect-road** [comment]
so how to solve this problem

**Comment by Linranran** [comment]
此次 commit 841be503f7bb6b9369cb666cabedf1048e1e1384修改了推理部分代码，对应的mai.py未修改
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/142#issuecomment-662262850

**Comment by wojiaohumaocheng** [comment]
I meet the same problem~

**Comment by lzw0515** [comment]
应该是3天前的这次改动带来的，我更新了代码以后也出现了这个问题，之前的代码没这个问题，输出outputs类型这次的是list，之前的是torch.tensor

**Comment by qybing** [comment]
我也遇到这样的问题，有解决方法吗

**Comment by PALMJJ** [comment]
> 
> 
> 应该是3天前的这次改动带来的，我更新了代码以后也出现了这个问题，之前的代码没这个问题，输出outputs类型这次的是list，之前的是torch.tensor

是的，我输出后outputs显示的是两个Tensor组成的list，暂时还不知道如何解决

**Comment by ersheng-ai** [comment]
Pull the latest code. Corresponding training code was updated by https://github.com/Tianxiaomo/pytorch-YOLOv4/pull/183

**Comment by ersheng-ai** [comment]
Modifications of https://github.com/Tianxiaomo/pytorch-YOLOv4/pull/183 is unfinished.
Current output bounding box format is [x1, y1, x2, y2], not [x_center, y_center, W, H].

In train.py, line 497 was changed from
```py
boxes[...,:2] = boxes[...,:2] - boxes[...,2:]/2  # to coco format
```
to
```py
boxes[...,2:] = boxes[...,2:] - boxes[...,:2] # Transform [x1, y1, x2, y2] to [x1, y1, w, h]
```

**Comment by PALMJJ** [comment]
> 
> 
> Modifications of #183 is unfinished.
> Current output bounding box format is [x1, y1, x2, y2], not [x_center, y_center, W, H].
> 
> In train.py, line 497 was changed from
> 
> ```python
> boxes[...,:2] = boxes[...,:2] - boxes[...,2:]/2  # to coco format
> ```
> 
> to
> 
> ```python
> boxes[...,2:] = boxes[...,2:] - boxes[...,:2] # Transform [x1, y1, x2, y2] to [x1, y1, w, h]
> ```

I got this problem again:
Traceback (most recent call last):
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 624, in <module>
    device=device, )
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 422, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "/home/hengyuli/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/hengyuli/pytorch-YOLOv4/train.py", line 490, in evaluate
    for img, target, (boxes, confs) in zip(images, targets, outputs):
ValueError: too many values to unpack (expected 2)

**Comment by MarvelousV** [comment]
hi, did you solve the problem?
