### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)#向大佬求助#help~~~

### ISSUE THREAD

**Issue by czx429006199604052115** [Tianxiaomo/pytorch-YOLOv4#194]
训练coins的时候报错：
2020-07-29 10:54:31,951 train.py[line:327] INFO: Starting training:
        Epochs:          300
        Batch size:      2
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   25
        Validation size: 25
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 3
        Train label path:/media/czx/czx/datasets/coins/train.txt
        Pretrained:      /media/czx/czx/datasets/models/yolov4.conv.137.pth
    
Epoch 1/300:   0%|        | 0/25 [00:00<?, ?img/s]/home/czx/.virtualenvs/charmvenv/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Epoch 1/300:  96%|▉| 24/25 [00:12<00:00,  2.52img/convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
in function convert_to_coco_api...
creating index...
index created!
torch.Size([22743, 1, 4]) torch.Size([22743, 1, 4])
(22743, 1, 4) pass
torch.Size([22743, 3]) torch.Size([22743, 3])
Epoch 1/300:  96%|▉| 24/25 [00:18<00:00,  1.30img/
Traceback (most recent call last):
  File "/media/czx/czx/mygit/pytorch-YOLOv4/train.py", line 627, in <module>
    device=device, )
  File "/media/czx/czx/mygit/pytorch-YOLOv4/train.py", line 425, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "/home/czx/.virtualenvs/charmvenv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/media/czx/czx/mygit/pytorch-YOLOv4/train.py", line 497, in evaluate
    boxes = boxes.squeeze(2).cpu().detach().numpy()
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

可以看到torch.Size([22743, 1, 4])的时候这句没问题，第二次循环torch.Size([22743, 3])就报错了，是我选择模型选错了吗？
The first for loop can pass while torch.Size([22743, 1, 4]),the second for loop goes wrong and I can see torch.Size([22743, 3]), code is here:
![图片](https://user-images.githubusercontent.com/38033269/88752087-9d6c4800-d18b-11ea-9217-e489eb32ee27.png)

**Comment by MrSunnyW** [comment]
我也是这个错误，兄弟你解决了吗？

**Comment by wangqingcai2013** [comment]
同问，我也遇到了。不知道有没有人解决了？

**Comment by wangqingcai2013** [comment]
同问，我也遇到相同问题，不知道有没有人已经解决了？

**Comment by Jinhui-Qin** [comment]
求助，同样的错误

**Comment by JiangMei0201** [comment]
同样错误

**Comment by codeBearll** [comment]
有人解决了或者知道怎么解决吗

**Comment by ShiqiLi047** [comment]
有人解决了或者知道怎么解决吗
