### ISSUE TITLE
Hello, I also have some problem with VOC dataset training. How do you solve it？I use the voc_label.py in https://github.com/AlexeyAB/darknet/scripts to process datasets to generate train,txt and val.txt ,then run train.py. What's wrong with me？I hope it can be answered.Thanks

### ISSUE THREAD

**Issue by jpf0429** [Tianxiaomo/pytorch-YOLOv4#206]
log file path:log/log_2020-08-01_15-48-51.txt
2020-08-01 15:48:52,185 train.py[line:611] INFO: Using device cuda
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
2020-08-01 15:49:04,407 train.py[line:327] INFO: Starting training:
        Epochs:          20
        Batch size:      16
        Subdivisions:    4
        Learning rate:   0.001
        Training size:   5717
        Validation size: 5823
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 20
        Train label path:train.txt
        Pretrained:
    
Epoch 1/20:   0%|       | 0/5717 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    device=device, )
  File "train.py", line 370, in train
    for i, batch in enumerate(train_loader):
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/home/jiapengfei/anaconda3/envs/yolo4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/home/jiapengfei/yolov4/dataset.py", line 297, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by zrqi** [comment]
I have this problem before, because my image path is wrong, you need to check if your image is damaged or the image path is wrong

**Comment by jpf0429** [comment]
> 我以前有过这个问题，因为我的图像路径是错误的，您需要检查您的图像是否损坏或图像路径是否错误。

How to find the wrong path? I print the img_path in dataset.py in line 295. 
 Epoch 1/20:   0%|      | 0/82081 [00:00<?, ?img/s]/data/home/jiapengfei/yolov4/data/cocodata/train2014/000000374001.jpg
the path is correct,so please help me find the problem ,thanks

**Comment by jpf0429** [comment]
I found the problem，the img_path is data/home/jiapengfei/yolov4/data/cocodata/train2014/000000374001.jpg,but in train2014,the name of the images is COCO_train2014_000000000009
