### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by charliewang789** [Tianxiaomo/pytorch-YOLOv4#217]
when I train, i got this error. thank you in advance for help.

 File "F:\AI\classification\pytorch-YOLOv4\train.py", line 371, in train
    for i, batch in enumerate(train_loader):
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\AI\classification\pytorch-YOLOv4\dataset.py", line 359, in __getitem__
    sheight, self.cfg.w, self.cfg.h)
  File "F:\AI\classification\pytorch-YOLOv4\dataset.py", line 84, in fill_truth_detection
    min_w_h = np.array([bboxes[:, 2] - bboxes[:, 0], bboxes[:, 3] - bboxes[:, 1]]).min()
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by morgankohler** [comment]
I have the same problem

**Comment by alrzmshy** [comment]
@charliewang789 @morgankohler  Do you have images with a single object in them? 
It seems like there's a bug in the code when it comes to this case. I just removed the images that have single objects in them and it managed to finish the training loop. I don't know how to fix the bug in the code yet.

**Comment by nanshenwei** [comment]
same problem with yolov4-tiny.cfg

**Comment by dang-qi** [comment]
It is probably because your data label starts from 1 instead of 0.

**Comment by jiawenhao2015** [comment]
> It is probably because your data label starts from 1 instead of 0.

it works！！！thank you！！！

**Comment by peter0512lee** [comment]
> It is probably because your data label starts from 1 instead of 0.

what do you mean?

**Comment by ZongDaa** [comment]
@dang-qi @jiawenhao2015 hello,How to solve this problem?Could you describe it in more detail
