### ISSUE TITLE
RuntimeError: The size of tensor a (52) must match the size of tensor b (76) at non-singleton dimension 3

### ISSUE THREAD

**Issue by niuwenju** [Tianxiaomo/pytorch-YOLOv4#218]
_Traceback (most recent call last):
  File "train.py", line 627, in <module>
    device=device, )
  File "train.py", line 380, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 249, in forward
    pred[..., 0] += self.grid_x[output_id]
RuntimeError: The size of tensor a (52) must match the size of tensor b (76) at non-singleton dimension 3_

own data:
classes=2
size=416x416

in file cfg.py i have set 

**Cfg.use_darknet_cfg = False
Cfg.cfgfile = os.path.join(_BASE_DIR, 'cfg', 'yolov4.cfg')

Cfg.batch = 64
Cfg.subdivisions = 16
Cfg.width = 416
Cfg.height = 416
Cfg.channels = 3
Cfg.momentum = 0.949
Cfg.decay = 0.0005
Cfg.angle = 0
Cfg.saturation = 1.5
Cfg.exposure = 1.5
Cfg.hue = .1

Cfg.learning_rate = 0.00261
Cfg.burn_in = 1000
Cfg.max_batches = 4000
Cfg.steps = [3200, 3600]
Cfg.policy = Cfg.steps
Cfg.scales = .1, .1

Cfg.cutmix = 0
Cfg.mosaic = 1

Cfg.letter_box = 0
Cfg.jitter = 0.2
Cfg.classes = 2
Cfg.track = 0
Cfg.w = Cfg.width
Cfg.h = Cfg.height
Cfg.flip = 1
Cfg.blur = 0
Cfg.gaussian = 0
Cfg.boxes = 60  # box num
Cfg.TRAIN_EPOCHS = 300**

**Comment by MBocchi** [comment]
Don't forget to also modify in _yolov4.cfg_ file the parameters (classes, max_batches, steps, filters) as you did in _cfg.py_

**Comment by niuwenju** [comment]
i have fix the error by updating this project.

**Comment by thanhtinhvan** [comment]
> i have fix the error by updating this project.

Hi @niuwenju , could you please share how did you fix it? I'm facing same issue

**Comment by niuwenju** [comment]
just update the project to the latest version

**Comment by thanhtinhvan** [comment]
> just update the project to the latest version

thanks. I will try

**Comment by rongrong9005** [comment]
Choose Image size 608*608. It works. I don't know why other size can not work.

**Comment by jdg900** [comment]
In line 93 of train.py, there is an image_size. modify it.

**Comment by weilanShi** [comment]
> _Traceback (most recent call last): File "train.py", line 627, in device=device, ) File "train.py", line 380, in train loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes) File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "train.py", line 249, in forward pred[..., 0] += self.grid_x[output_id] RuntimeError: The size of tensor a (52) must match the size of tensor b (76) at non-singleton dimension 3_
> 
> own data:
> classes=2
> size=416x416
> 
> in file cfg.py i have set
> 
> **Cfg.use_darknet_cfg = False
> Cfg.cfgfile = os.path.join(_BASE_DIR, 'cfg', 'yolov4.cfg')
> 
> Cfg.batch = 64
> Cfg.subdivisions = 16
> Cfg.width = 416
> Cfg.height = 416
> Cfg.channels = 3
> Cfg.momentum = 0.949
> Cfg.decay = 0.0005
> Cfg.angle = 0
> Cfg.saturation = 1.5
> Cfg.exposure = 1.5
> Cfg.hue = .1
> 
> Cfg.learning_rate = 0.00261
> Cfg.burn_in = 1000
> Cfg.max_batches = 4000
> Cfg.steps = [3200, 3600]
> Cfg.policy = Cfg.steps
> Cfg.scales = .1, .1
> 
> Cfg.cutmix = 0
> Cfg.mosaic = 1
> 
> Cfg.letter_box = 0
> Cfg.jitter = 0.2
> Cfg.classes = 2
> Cfg.track = 0
> Cfg.w = Cfg.width
> Cfg.h = Cfg.height
> Cfg.flip = 1
> Cfg.blur = 0
> Cfg.gaussian = 0
> Cfg.boxes = 60 # box num
> Cfg.TRAIN_EPOCHS = 300**

set the size to 608*608, it‘s work

**Comment by pursuityu** [comment]
in the train.py, you should modify image_size:

class Yolo_loss(nn.Module):
    def __init__(self, n_classes=80, n_anchors=3, device=None, batch=2):
        super(Yolo_loss, self).__init__()
        self.device = device
        self.strides = [8, 16, 32]
        image_size = 416  #608

**Comment by liuyangly1** [comment]
I meet the same problem, if we can modify it as follows,  it can train. But I have another problem, all AP results are 0. 
1. in the cfg.py  27 line and 28 line, Cfg.width=1024 and Cfg.height=1024.
2. in the cfg/yolov4.cfg 8 line and 9 line, width=1024 and height=1024.
3. in the train.py 134 line and 135 line, self.strides = [32,16, 8] # [8, 16, 32] and image_size=1024

**Comment by liuyangly1** [comment]
I meet the same problem and solve it. The dataset format should is VOC instead of COCO, and you should change image_size in train.py.

**Comment by mostafa-zaghloul** [comment]
The Yolo_loss function parameters wasn't passed by reference, so if your values aren't a match with it's defaults train function crashes.. it's a simple bug.
