### ISSUE TITLE
Error when deal with the picture after load it 

### ISSUE THREAD

**Issue by niuwenju** [Tianxiaomo/pytorch-YOLOv4#220]
when i training it with my own data,i always get the same error as follows(but diffenrent picture), but i have check the dataset,there is no problem. so i think maybe it cause the muti-threading.

Epoch 1/300:  17%|▏| 11944/68923 [15:07<1:12:11, 1
Traceback (most recent call last):
  File "train.py", line 626, in <module>
/home/yons/Downloads/darknet/VOCdevkit/VOC2007/JPEGImages/000000301209.jpg
    device=device, )
  File "train.py", line 370, in train
    for i, batch in enumerate(train_loader):
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yons/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yons/Downloads/pytorch-YOLOv4/dataset.py", line 298, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by aleenakvk** [comment]
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/259#issuecomment-703499850 refer this. I had the same problem.
