### ISSUE TITLE
RuntimeError: CUDA out of memory.   How to solve？

### ISSUE THREAD

**Issue by zhangmingjiang1114** [Tianxiaomo/pytorch-YOLOv4#229]
I have set the parameters in cfg.py as follows:
Cfg.use_darknet_cfg = False  
Cfg.cfgfile = os.path.join(_BASE_DIR, 'cfg', 'yolov4.cfg') 
And set the parameters in  yolov4.cfg  as follows: 
 classes=3,  filters=24   in 3 places. 
But the program still reports the following error:

E:\pytorch-YOLOv4-master>python train.py -l 0.001 -g 0 -pretrained ./weigh/yolov4.conv.137.pth -classes 3 -dir ./voc/coins -train_label_path ./voc/coins/train.txt
log file path:log\log_2020-08-17_14-53-48.txt
2020-08-17 14:53:49,666 train.py[line:611] INFO: Using device cuda
2020-08-17 14:53:53,123 train.py[line:327] INFO: Starting training:
        Epochs:          1
        Batch size:      1
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   25
        Validation size: 4
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 3
        Train label path:./voc/coins/train.txt
        Pretrained:

Epoch 1/1:   8%|▏ | 2/25 [00:12<02:22,  6.21s/img]
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    device=device, )
  File "train.py", line 379, in train
    bboxes_pred = model(images)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\pytorch-YOLOv4-master\models.py", line 448, in forward
    output = self.head(x20, x13, x6)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\pytorch-YOLOv4-master\models.py", line 392, in forward
    x14 = self.conv14(x13)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\pytorch-YOLOv4-master\models.py", line 65, in forward
    x = l(x)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\modules\batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "E:\Anaconda3\envs\yolov4\lib\site-packages\torch\nn\functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 2.90 GiB already allocated; 806.40 KiB free; 2.97 GiB reserved in total by PyTorch)

How to solve it?  Thank you!!!

**Comment by AnkitGoyal430** [comment]
I think this is simply because of not enough GPU memory.
When I tried it takes around 10GB GPU memory. 
You need bigger GPU memory size to train this.

**Comment by Carryma11** [comment]
Yolov4 concumes more GPU memeoy by yolov3,in fect it will be better if you have 11GB memeoy at least(GTX2080ti or higher).
Otherwise you can only decrease the batch size and the image size(to 416,320...) to get it, but the performance will be a lillte bad.

**Comment by zhangmingjiang1114** [comment]
> Yolov4 concumes more GPU memeoy by yolov3,in fect it will be better if you have 11GB memeoy at least(GTX2080ti or higher).
> Otherwise you can only decrease the batch size and the image size(to 416,320...) to get it, but the performance will be a lillte bad.

谢谢！！！

**Comment by soHardToHaveAName** [comment]
> Yolov4 concumes more GPU memeoy by yolov3,in fect it will be better if you have 11GB memeoy at least(GTX2080ti or higher).
> Otherwise you can only decrease the batch size and the image size(to 416,320...) to get it, but the performance will be a lillte bad.

How can I decrease the batch size? (only found 'batch=64' in yolov4.cfg)
