### ISSUE TITLE
solved an Error about COCO evaluate for training yourself dataset

### ISSUE THREAD

**Issue by onmywei** [Tianxiaomo/pytorch-YOLOv4#231]
When training yourself dataset, the following errors are likely to occur:

`Traceback (most recent call last):
  File "/home/ypl/projects/pytorch-YOLOv4/inference_data_test.py", line 393, in <module>
    print(evaluate(model,val_loader,config,'cuda:1'))
  File "/home/ypl/anaconda3/envs/pytorch1.4/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ypl/projects/pytorch-YOLOv4/inference_data_test.py", line 367, in evaluate
    coco_evaluator.update(res)
  File "/home/ypl/projects/pytorch-YOLOv4/tool/tv_reference/coco_eval.py", line 41, in update
    coco_dt = loadRes(self.coco_gt, results) if results else COCO()
  File "/home/ypl/projects/pytorch-YOLOv4/tool/tv_reference/coco_eval.py", line 278, in loadRes
    x1, x2, y1, y2 = bb[0], bb[0] + bb[2], bb[1], bb[1] + bb[3]
IndexError: list index out of range`
or 
`Traceback (most recent call last):
  File "/home/ypl/projects/pytorch-YOLOv4/inference_data_test.py", line 393, in <module>
    print(evaluate(model,val_loader,config,'cuda:1'))
  File "/home/ypl/anaconda3/envs/pytorch1.4/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ypl/projects/pytorch-YOLOv4/inference_data_test.py", line 367, in evaluate
    coco_evaluator.update(res)
  File "/home/ypl/projects/pytorch-YOLOv4/tool/tv_reference/coco_eval.py", line 46, in update
    img_ids, eval_imgs = evaluate(coco_eval)
  File "/home/ypl/projects/pytorch-YOLOv4/tool/tv_reference/coco_eval.py", line 338, in evaluate
    self.ious = {
  File "/home/ypl/projects/pytorch-YOLOv4/tool/tv_reference/coco_eval.py", line 339, in <dictcomp>
    (imgId, catId): computeIoU(imgId, catId)
  File "/home/ypl/anaconda3/envs/pytorch1.4/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 190, in computeIoU
    ious = maskUtils.iou(d,g,iscrowd)
  File "pycocotools/_mask.pyx", line 214, in pycocotools._mask.iou
  File "pycocotools/_mask.pyx", line 193, in pycocotools._mask.iou._preproc
Exception: list input can be bounding box (Nx4) or RLEs ([RLE])`

The reason is the two inputs of COCOeval.evaluate() function: coco_gt and Coco_dt. They are instances of COCO class, so they should have the same data structure. But we end up with a 'bbox' property that has a different value: coco_gt is a list :[X,Y,H,W] and coco_dt is a nested list:[[X,Y,H,W]].
you can refer to #230  for simple modifications.

**Comment by ersheng-ai** [comment]
Pull request is merged
