### ISSUE TITLE
训练自己的数据集，怎么用cocoapi验证

### ISSUE THREAD

**Issue by 1962975362** [Tianxiaomo/pytorch-YOLOv4#237]
Epoch 1/30: 100%|█| 16/16 [00:04<00:00,  3.55img/s
Traceback (most recent call last):
  File "/home/user/lyf/PycharmProjects/YOLOv4/YOLOv4/train.py", line 626, in <module>
    device=device, )
  File "/home/user/lyf/PycharmProjects/YOLOv4/YOLOv4/train.py", line 423, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "/home/user/lyf/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/user/lyf/PycharmProjects/YOLOv4/YOLOv4/train.py", line 513, in evaluate
    coco_evaluator.update(res)
  File "/home/user/lyf/PycharmProjects/YOLOv4/YOLOv4/tool/tv_reference/coco_eval.py", line 46, in update
    img_ids, eval_imgs = evaluate(coco_eval)
  File "/home/user/lyf/PycharmProjects/YOLOv4/YOLOv4/tool/tv_reference/coco_eval.py", line 328, in evaluate
    self._prepare()
  File "/home/user/lyf/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/cocoeval.py", line 97, in _prepare
    dts=self.cocoDt.loadAnns(self.cocoDt.getAnnIds(imgIds=p.imgIds, catIds=p.catIds))
  File "/home/user/lyf/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 148, in getAnnIds
    anns = self.dataset['annotations']
KeyError: 'annotations'

Process finished with exit code 1

**Comment by 1962975362** [comment]
怎么配置自己的数据集

**Comment by sangwz** [comment]
问题搞定了吗
