### ISSUE TITLE
Model - weights mismatch issue

### ISSUE THREAD

**Issue by tantayo** [Tianxiaomo/pytorch-YOLOv4#244]
Just starting to try it by inferencing on single image. Downloaded already converted pytorch weights. However when trying something like:

python models.py 20 ./weights/yolov4.pth ./VOC/test/images/000001.jpg 320 320

will get:
Traceback (most recent call last):
  File "models.py", line 477, in <module>
    model.load_state_dict(pretrained_dict)
  File "/home/santiago/projects/pytorch/install/lib/python3.8/site-packages/torch/nn/modules/module.py", line 829, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Yolov4:
	size mismatch for head.conv2.conv.0.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 256, 1, 1]).
	size mismatch for head.conv2.conv.0.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).
	size mismatch for head.conv10.conv.0.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 512, 1, 1]).
	size mismatch for head.conv10.conv.0.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).
	size mismatch for head.conv18.conv.0.weight: copying a param with shape torch.Size([255, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([75, 1024, 1, 1]).
	size mismatch for head.conv18.conv.0.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([75]).

And trying the other weights (yolov4.conv.137.pth) will get missing keys:

File "models.py", line 477, in <module>
    model.load_state_dict(pretrained_dict)
  File "/home/santiago/projects/pytorch/install/lib/python3.8/site-packages/torch/nn/modules/module.py", line 829, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Yolov4:
	Missing key(s) in state_dict: "head.conv1.conv.0.weight", "head.conv1.conv.1.weight", "head.conv1.conv.1.bias", "head.conv1.conv.1.running_mean", "head.conv1.conv.1.running_var", "head.conv2.conv.0.weight", "head.conv2.conv.0.bias", "head.conv3.conv.0.weight", "head.conv3.conv.1.weight", "head.conv3.conv.1.bias", "head.conv3.conv.1.running_mean", "head.conv3.conv.1.running_var", "head.conv4.conv.0.weight", "head.conv4.conv.1.weight", "head.conv4.conv.1.bias", "head.conv4.conv.1.running_mean", "head.conv4.conv.1.running_var", "head.conv5.conv.0.weight", "head.conv5.conv.1.weight", "head.conv5.conv.1.bias", "head.conv5.conv.1.running_mean", "head.conv5.conv.1.running_var", "head.conv6.conv.0.weight", "head.conv6.conv.1.weight", "head.conv6.conv.1.bias", "head.conv6.conv.1.running_mean", "head.conv6.conv.1.running_var", "head.conv7.conv.0.weight", "head.conv7.conv.1.weight", "head.conv7.conv.1.bias", "head.conv7.conv.1.running_mean", "head.conv7.conv.1.running_var", "head.conv8.conv.0.weight", "head.conv8.conv.1.weight", "head.conv8.conv.1.bias", "head.conv8.conv.1.running_mean", "head.conv8.conv.1.running_var", "head.conv9.conv.0.weight", "head.conv9.conv.1.weight", "head.conv9.conv.1.bias", "head.conv9.conv.1.running_mean", "head.conv9.conv.1.running_var", "head.conv10.conv.0.weight", "head.conv10.conv.0.bias", "head.conv11.conv.0.weight", "head.conv11.conv.1.weight", "head.conv11.conv.1.bias", "head.conv11.conv.1.running_mean", "head.conv11.conv.1.running_var", "head.conv12.conv.0.weight", "head.conv12.conv.1.weight", "head.conv12.conv.1.bias", "head.conv12.conv.1.running_mean", "head.conv12.conv.1.running_var", "head.conv13.conv.0.weight", "head.conv13.conv.1.weight", "head.conv13.conv.1.bias", "head.conv13.conv.1.running_mean", "head.conv13.conv.1.running_var", "head.conv14.conv.0.weight", "head.conv14.conv.1.weight", "head.conv14.conv.1.bias", "head.conv14.conv.1.running_mean", "head.conv14.conv.1.running_var", "head.conv15.conv.0.weight", "head.conv15.conv.1.weight", "head.conv15.conv.1.bias", "head.conv15.conv.1.running_mean", "head.conv15.conv.1.running_var", "head.conv16.conv.0.weight", "head.conv16.conv.1.weight", "head.conv16.conv.1.bias", "head.conv16.conv.1.running_mean", "head.conv16.conv.1.running_var", "head.conv17.conv.0.weight", "head.conv17.conv.1.weight", "head.conv17.conv.1.bias", "head.conv17.conv.1.running_mean", "head.conv17.conv.1.running_var", "head.conv18.conv.0.weight", "head.conv18.conv.0.bias"

**Comment by tigerdhl** [comment]
I get the same problem, do you solve it?

**Comment by ohsai** [comment]
Try it with num_classes 80, instead of 20.

**Comment by mhasnat** [comment]
I was not able to solve this problem after changing the num_classes from 80 to 20 for the VOC data training. Can anyone please tell what are the alternative solution?

**Comment by adrien-jacquot** [comment]
Hey, I found a way to properly load the model (don't ask me why it works):

```python
model = Yolov4(yolov4conv137weight=None, n_classes=1, inference=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
model.to(device=device)
pretrained_dict = torch.load(model_path, map_location=torch.device('cuda'))
model.load_state_dict(pretrained_dict)
model.cuda()
```

**Comment by CongSuxu** [comment]
just use the load weight function in Yolov4.init()

**Comment by santi-mir** [comment]
I think this is a problem with config files overwriting stuff. You can convert the model and pass -f path/to/model.pth
