### ISSUE TITLE
如何解决 "NotImplementedError: Create your own 'get_image_id' function"

### ISSUE THREAD

**Issue by zhangmingjiang1114** [Tianxiaomo/pytorch-YOLOv4#254]
用的是作者的coins数据集，报错如下：
(yolov4) E:\pytorch-YOLOv4-master>python train.py -l 0.001 -g 0 -pretrained ./weigh/yolov4.conv.137.pth -classes 3 -dir ./voc/coins -train_label_path ./voc/coins/train.txt
log file path:log\log_2020-08-29_20-44-25.txt
2020-08-29 20:44:26,687 train.py[line:620] INFO: Using device cuda
2020-08-29 20:44:29,224 train.py[line:327] INFO: Starting training:
        Epochs:          5
        Batch size:      4
        Subdivisions:    2
        Learning rate:   0.001
        Training size:   25
        Validation size: 4
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 3
        Train label path:E:\pytorch-YOLOv4-master\voc\coins\train.txt
        Pretrained:

Epoch 1/5:  96%|▉| 24/25 [00:17<00:00,  2.03img/s]in function convert_to_coco_api...
Epoch 1/5:  96%|▉| 24/25 [00:18<00:00,  1.29img/s]
Traceback (most recent call last):
  File "train.py", line 635, in <module>
    device=device, )
  File "train.py", line 425, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "D:\Anaconda3\envs\yolov4\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "train.py", line 471, in evaluate
    coco = convert_to_coco_api(data_loader.dataset, bbox_fmt='coco')
  File "E:\pytorch-YOLOv4-master\tool\tv_reference\coco_utils.py", line 158, in convert_to_coco_api
    img, targets = ds[img_idx]
  File "E:\pytorch-YOLOv4-master\dataset.py", line 271, in __getitem__
    return self._get_val_item(index)
  File "E:\pytorch-YOLOv4-master\dataset.py", line 406, in _get_val_item
    target['image_id'] = torch.tensor([get_image_id(img_path)])
  File "E:\pytorch-YOLOv4-master\dataset.py", line 426, in get_image_id
    raise NotImplementedError("Create your own 'get_image_id' function")
NotImplementedError: Create your own 'get_image_id' function

非常感谢！

**Comment by yuxx0218** [comment]
you can see my pull request on this project.

**Comment by zhangmingjiang1114** [comment]
> you can see my pull request on this project.

非常感谢！已经解决！！

**Comment by liuwenhua6666** [comment]
遇到同样问题，你是怎样解决得？谢谢

**Comment by zhangmingjiang1114** [comment]
> 遇到同样问题，你是怎样解决得？谢谢

def get_image_id(filename:str) -> int:
    """
    Convert a string to a integer.
    Make sure that the images and the `image_id`s are in one-one correspondence.
    There are already `image_id`s in annotations of the COCO dataset,
    in which case this function is unnecessary.
    For creating one's own `get_image_id` function, one can refer to
    https://github.com/google/automl/blob/master/efficientdet/dataset/create_pascal_tfrecord.py#L86
    or refer to the following code (where the filenames are like 'level1_123.jpg')
    >>> lv, no = os.path.splitext(os.path.basename(filename))[0].split("_")
    >>> lv = lv.replace("level", "")
    >>> no = f"{int(no):04d}"
    >>> return int(lv+no)
    """

    # raise NotImplementedError("Create your own 'get_image_id' function")
    # lv, no = os.path.splitext(os.path.basename(filename))[0].split("_")
    # lv = lv.replace("level", "")
    # no = f"{int(no):04d}"
    # return int(lv+no)

    print("You could also create your own 'get_image_id' function.")
    # print(filename)
    parts = filename.split('-')
    id = int(parts[-1][0:-4])
    # print(id)
    return id

**Comment by EternalEvan** [comment]
I solved the problem in your way. But I'll get stuck in the first epoch.

2020-10-30 14:35:53,703 train.py[line:611] INFO: Using device cuda
2020-10-30 14:35:56,377 train.py[line:327] INFO: Starting training:
        Epochs:          5
        Batch size:      4
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   21
        Validation size: 4
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 3
        Train label path:data/train.txt
        Pretrained:
    
Epoch 1/5:  95%|▉| 20/21 [00:16<00:00,  1.01img/s]in function convert_to_coco_api...
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
creating index...
index created!

 Can you share how you train the coins images provided by the anthors or share your files. Thank you very much!

**Comment by Rich2333** [comment]
> I solved the problem in your way. But I'll get stuck in the first epoch.
> 
> 2020-10-30 14:35:53,703 train.py[line:611] INFO: Using device cuda
> 2020-10-30 14:35:56,377 train.py[line:327] INFO: Starting training:
> Epochs: 5
> Batch size: 4
> Subdivisions: 1
> Learning rate: 0.001
> Training size: 21
> Validation size: 4
> Checkpoints: True
> Device: cuda
> Images size: 608
> Optimizer: adam
> Dataset classes: 3
> Train label path:data/train.txt
> Pretrained:
> 
> Epoch 1/5: 95%|▉| 20/21 [00:16<00:00, 1.01img/s]in function convert_to_coco_api...
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> creating index...
> index created!
> 
> Can you share how you train the coins images provided by the anthors or share your files. Thank you very much!

I use the same code and then it shows:
Epoch 1/300:  96%|▉| 24/25 [02:24<00:06,  6.06s/imin function convert_to_coco_api...
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
You could also create your own 'get_image_id' function.
creating index...
index created!
Epoch 1/300:  96%|▉| 24/25 [02:29<00:06,  6.23s/im
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    device=device, )
  File "train.py", line 425, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "C:\ProgramData\Anaconda3\envs\torch_cpu\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 472, in evaluate
    coco_evaluator = CocoEvaluator(coco, iou_types = ["bbox"], bbox_fmt='coco')
  File "C:\Users\rich\Desktop\pytorch-YOLOv4-master\tool\tv_reference\coco_eval.py", line 30, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "C:\ProgramData\Anaconda3\envs\torch_cpu\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "C:\ProgramData\Anaconda3\envs\torch_cpu\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "C:\ProgramData\Anaconda3\envs\torch_cpu\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\ProgramData\Anaconda3\envs\torch_cpu\lib\site-packages\numpy\core\function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by Fushier** [comment]
> I solved the problem in your way. But I'll get stuck in the first epoch.
> 
> 2020-10-30 14:35:53,703 train.py[line:611] INFO: Using device cuda
> 2020-10-30 14:35:56,377 train.py[line:327] INFO: Starting training:
> Epochs: 5
> Batch size: 4
> Subdivisions: 1
> Learning rate: 0.001
> Training size: 21
> Validation size: 4
> Checkpoints: True
> Device: cuda
> Images size: 608
> Optimizer: adam
> Dataset classes: 3
> Train label path:data/train.txt
> Pretrained:
> 
> Epoch 1/5: 95%|▉| 20/21 [00:16<00:00, 1.01img/s]in function convert_to_coco_api...
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> You could also create your own 'get_image_id' function.
> creating index...
> index created!
> 
> Can you share how you train the coins images provided by the anthors or share your files. Thank you very much!

I also get stuck in the first epoch. Do you solve this problem?
