### ISSUE TITLE
UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by Juuustin** [Tianxiaomo/pytorch-YOLOv4#256]
There is another error when I run on my own data:
Traceback (most recent call last):
  File "train.py", line 616, in <module>
    model = Yolov4(cfg.pretrained, n_classes=cfg.classes)
  File "D:\study\Dinosaour\pytorch-YOLOv4\models.py", line 426, in __init__
    pretrained_dict = torch.load(yolov4conv137weight)
  File "C:\Users\onthe\Anaconda3\lib\site-packages\torch\serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\onthe\Anaconda3\lib\site-packages\torch\serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.
Any suggestions?

**Comment by Pooya-Mohammadi-K** [comment]
I changed the filters, as mentioned in [https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/138#issuecomment-721116468](https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/138#issuecomment-721116468).

**Comment by mfoglio** [comment]
How to I solved this? I have the same issue.

**Comment by DeviAyyagari** [comment]
Have you been able to resolve this issue? I am seeing the same issue "_pickle.UnpicklingError: invalid load key, '\x00'." and would appreciate your help. Thank you!
