### ISSUE TITLE
Runtime error while running train.py

### ISSUE THREAD

**Issue by mbpictures** [Tianxiaomo/pytorch-YOLOv4#263]
Hi!

I just wanted to run the train.py script and it gave me the following output:
```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    from tool.tv_reference.coco_utils import convert_to_coco_api
  File "A:\Projects\pytorch-YOLOv4\tool\tv_reference\coco_utils.py", line 7, in <module>
    import torchvision
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import models
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\models\__init__.py", line 12, in <module>
    from . import detection
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "C:\Users\mbcub\AppData\Local\Programs\Python\Python37\lib\site-packages\torchvision\ops\boxes.py", line 43, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
```

Do you have any idea how to fix this?

**Comment by lwj981024** [comment]
hello this might be pytorch problem.
I saved it by using
pip3 install torchvision==0.4.0
