### ISSUE TITLE
How to prepare 'val.txt' on our own dataset?

### ISSUE THREAD

**Issue by jayhung97724** [Tianxiaomo/pytorch-YOLOv4#266]
Hello there, I've tried to train on my own dataset, and I have created training image and 'train.txt' well.
But then when I tried to train I got this:
```
train.py[line:611] INFO: Using device cuda
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    device=device, )
  File "train.py", line 293, in train
    val_dataset = Yolo_dataset(config.val_label, config, train=False)
  File "D:\Code\yolo\pytorch-YOLOv4\dataset.py", line 256, in __init__
    f = open(lable_path, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'pytorch-YOLOv4\\data\\val.txt'
```
Can someone provide more info of training own dataset?

**Comment by xielu6** [comment]
I also encountered the same problem, did you solve it?

**Comment by zxj11838** [comment]
You can refer to this file (Use_yolov4_to_train_your_own_data.md）in the project.
