### ISSUE TITLE
how to convert darknet  .weight to pytorch .pt file

### ISSUE THREAD

**Issue by songzhifei** [Tianxiaomo/pytorch-YOLOv4#281]
I have trained based on darknet-yolov4 and get .weight file. how can i convert it to pytorch .pth file. i have tried to use darknet2pytorch.py. i use the .pth and it report an erro like this：

  File "models.py", line 476, in <module>
    pretrained_dict = torch.load(weightfile)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by githubfragments** [comment]
@I also encountered this problem in windows, but this problem have not appeared in linux. How to fix it in windows?

**Comment by Linchunhui** [comment]
darknet2pytorch.py 里用Darknet构建模型后，load_weights，最后torch.save就好了

**Comment by ajsanjoaquin** [comment]
> darknet2pytorch.py 里用Darknet构建模型后，load_weights，最后torch.save就好了

How exactly do you use torch.save on the .weights file you just loaded? I'm having the exact problem as OP.

**Comment by ryj0902** [comment]
Does the same problem occur after running the code below?

```
from tool import darknet2pytorch
import torch

# load weights from darknet format
model = darknet2pytorch.Darknet('path/to/cfg/yolov4-416.cfg', inference=True)
model.load_weights('path/to/weights/yolov4-416.weights')

# save weights to pytorch format
torch.save(model.state_dict(), 'path/to/save/yolov4-pytorch.pth')

# reload weights from pytorch format
model_pt = darknet2pytorch.Darknet('path/to/cfg/yolov4-416.cfg', inference=True)
model_pt.load_state_dict(torch.load('path/to/save/yolov4-pytorch.pth'))
```

**Comment by ajsanjoaquin** [comment]
Thank you this solves it. However, I am getting a false warning from output that the linear activation for the convolutional blocks aren't initialized when loading the yolov4.cfg. The code runs fine on the demo images regardless. I will fix this with a PR.

**Comment by vishnuvardhan58** [comment]
Hello , i am getting the following error when using the above script for conversion of yolov4 weights to pytorch         

   [
<img width="453" alt="error" src="https://user-images.githubusercontent.com/9161539/104378163-ed528780-54fd-11eb-8769-92e6b309f8d6.PNG">
](url)

**Comment by vishnuvardhan58** [comment]
Hello , i have used the above script to convert yolov4 darknet weights to pytorch weights , I am getting the following as shown below 
<img width="470" alt="error" src="https://user-images.githubusercontent.com/9161539/104382896-5a1d5000-5505-11eb-9993-0eee9eda7f00.PNG">

**Comment by ajsanjoaquin** [comment]
> Hello , i have used the above script to convert yolov4 darknet weights to pytorch weights , I am getting the following as shown below ,
> <img alt="error" width="470" src="https://user-images.githubusercontent.com/9161539/104382896-5a1d5000-5505-11eb-9993-0eee9eda7f00.PNG">
> 
It's a false warning and it should not impact your model's performance. If you want to get rid of it, you can copy the code I wrote in the PR I opened for this issue.

> and when I am running the prediction on video using this weights I am getting the following error
> 
> <img alt="error" width="869" src="https://user-images.githubusercontent.com/9161539/104383015-8507a400-5505-11eb-8128-8c06f1b7d1c2.PNG">

"yolov4demo.py" isn't a file in this repo.  From the traceback, it seems you have to call on a method on your `model` object before loading the state_dict.

**Comment by vishnuvardhan58** [comment]
Hello @ajsanjoaquin , thankyou for your reply.

**Comment by laoshaw** [comment]
a related question, how to convert pytorch pt file to darknet .weight file?

**Comment by chandu1263** [comment]
@laoshaw  were you able to convert pt file to weight file?

**Comment by laoshaw** [comment]
looks like only for yolo3, but I actually did not test it eventually, the answer is no

**Comment by gauravgund** [comment]
@ryj0902 I am getting error while importing tool. The error is as follows:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-50-dc3eb14a3886> in <module>()
----> 1 from tool.darknet2pytorch import *
      2 WEIGHTS = Darknet(cfgfile)
      3 WEIGHTS.load_weights(weightfile)

/usr/local/lib/python3.7/dist-packages/tool/__init__.py in <module>()
      9 #  Software Foundation. See the file README for copying conditions.
     10 #
---> 11 from context_locals import app, local
     12 from application import Application, WebApplication #, current_app as app
     13 

ModuleNotFoundError: No module named 'context_locals'


I did 'pip install tool'. Could you help?

**Comment by ryj0902** [comment]
@gauravgund  
Code should run on the top-level folder of this repository.  
So the module imported here should be `/pytorch-YOLOv4/tool`, not `/usr/local/lib/python3.7/dist-packages/tool`.

**Comment by gauravgund** [comment]
@ryj0902 : I am able to convert it into .pth. But when i am trying to run TTA using https://github.com/kentaroy47/ODA-Object-Detection-ttA

I am getting an error pertaining to pytorch-YOLOv4 which means the conversion has not happened correctly:


/content/pytorch-YOLOv4/tool/darknet2pytorch.py in forward(self, x)
    224             return out_boxes
    225         else:
--> 226             return get_region_boxes(out_boxes)
    227 
    228     def print_network(self):

/content/pytorch-YOLOv4/tool/torch_utils.py in get_region_boxes(boxes_and_confs)
     55     for item in boxes_and_confs:
     56         boxes_list.append(item[0])
---> 57         confs_list.append(item[1])
     58 
     59     # boxes: [batch, num1 + num2 + num3, 1, 4]

IndexError: index 1 is out of bounds for dimension 0 with size 1'

**Comment by gauravgund** [comment]
yes, my yolo model is working fine using open-cv. Just that i wanted to try
tta and weight-box fusion.

**Comment by ryj0902** [comment]
@gauravgund well..., I am not sure what is causing this problem.
It seems good to open up to other issues and ask others for help.

**Comment by thatITfox** [comment]
hey there, i was wondering on how do i input the images and how do i output them from the pytorch model, is there a script i can use? or what should i do?

**Comment by ryj0902** [comment]
@thatITfox I think [demo.py](https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/demo.py) can help you.
code below shows you how to load a model from pytorch model.
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/a65d219f9066bae4e12003bd7cdc04531860c672/demo.py#L65-L67
although code from another function, you can process image as follows.
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/a65d219f9066bae4e12003bd7cdc04531860c672/demo.py#L46-L57
If you curious about the preprocessing and postprocessing(a.k.a. NMS) see `do_detect` function. (actually, excluding pre/post-processing, the model execution code is only one line.)

**Comment by thatITfox** [comment]
thanks dude 👍

**Comment by journeytosilius** [comment]
hi, can I use this tool to convert Yolo9000 weights to .pt usable with Yolo 5 or 7 ? 

Thanks

**Comment by MrMaynard** [comment]
This is not usable for YOLO 8:
```
    args = {**DEFAULT_CFG_DICT, **ckpt['train_args']}  # combine model and default args, preferring model args
KeyError: 'train_args'
```

**Comment by mathur01** [comment]
Hi @ryj0902 ,
I am getting error while running above mentioned code. 
 ```
from context_locals import app, local
ModuleNotFoundError: No module named 'context_locals'
```

code is as follows:
```
import torch

from tool.darknet2pytorch import Darknet
WEIGHTS = Darknet('xyz.cfg',inference=True)
WEIGHTS.load_weights('xyz.weights')
```
looks like tool package is giving error. 
Also tool is installed in my conda environment.
`tool                      0.8.0`

**Comment by ryj0902** [comment]
@mathur01 I think the issue seems to be the same cause as [mentioned above](https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/281#issuecomment-835822081).

> Code should run on the top-level folder of this repository. So the module imported here should be `/pytorch-YOLOv4/tool`, not `/usr/local/lib/python3.7/dist-packages/tool`.

The `tool` package mentioned in the code refers to **Tianxiaomo/pytorch-YOLOv4/tool**, not the `tool 0.8.0` provided by pypi(as you mentioned). 

(Though I don't know exactly,) based on the priority of importing libraries in Python, if you import a package with the same name, the **folder in the directory where you run the code** is referenced first.

So, don't run that code in arbitrary path, but try to run it exactly under the Tianxiaomo/pytorch-YOLOv4 directory.

**Comment by tobymuller233** [comment]
Is the converting script compatible for all darknet models? I got a model which is not yolov4, yoloface-500k from another repo, when i tried to run the script, errors occur when reshaping.
<img width="942" alt="Screenshot 2024-10-14 at 11 34 01" src="https://github.com/user-attachments/assets/6b07a7bf-a524-496e-8342-d63a1c20e5bd">
Or is it just a mistake that the model designer made?
By the way, there are some route and shortcut components in this yoloface-500k model and I think maybe that's the problem.

**Comment by tobymuller233** [comment]
> Is the converting script compatible for all darknet models? I got a model which is not yolov4, yoloface-500k from another repo, when i tried to run the script, errors occur when reshaping. <img alt="Screenshot 2024-10-14 at 11 34 01" width="942" src="https://private-user-images.githubusercontent.com/100904932/376101398-6b07a7bf-a524-496e-8342-d63a1c20e5bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzcxMjIsIm5iZiI6MTcyODg3NjgyMiwicGF0aCI6Ii8xMDA5MDQ5MzIvMzc2MTAxMzk4LTZiMDdhN2JmLWE1MjQtNDk2ZS04MzQyLWQ2M2ExYzIwZTViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwMzMzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzJlMDU4ZWRjMzZiZmMzMTFhOTIzMjQzNmRjYjBkYWQyMDllY2QyOWJmZGQxYzNhMmM4NGM3NmQ1MjM3YjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ka06FKvmjNqGaLxE8LGegLd0YGlw140dnFcZ4u9xl3k"> Or is it just a mistake that the model designer made? By the way, there are some route and shortcut components in this yoloface-500k model and I think maybe that's the problem.

It seems that the buf array here is not big enough to store too much data at every single moment.
<img width="131" alt="Screenshot 2024-10-14 at 11 42 31" src="https://github.com/user-attachments/assets/9e50b003-2297-4eaa-bcd2-390420c40e97">
