### ISSUE TITLE
训练的时候，配置出现的问题

### ISSUE THREAD

**Issue by jaguarzhang** [Tianxiaomo/pytorch-YOLOv4#293]
D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\python.exe E:/PycharmProjects/pytorch-YOLOv4/train.py
log file path:log\log_2020-10-13_17-06-25.txt
2020-10-13 17:06:25,341 train.py[line:611] INFO: Using device cuda
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
2020-10-13 17:06:26,792 train.py[line:327] INFO: Starting training:
        Epochs:          300
        Batch size:      4
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   1156
        Validation size: 276
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 80
        Train label path:E:/PycharmProjects/pytorch-YOLOv4/data/train.txt
        Pretrained:
    
Epoch 1/300:   0%|      | 0/1156 [00:10<?, ?img/s]
Traceback (most recent call last):
  File "E:/PycharmProjects/pytorch-YOLOv4/train.py", line 626, in <module>
    device=device, )
  File "E:/PycharmProjects/pytorch-YOLOv4/train.py", line 370, in train
    for i, batch in enumerate(train_loader):
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\app\anaconda3\envs\Yet-Another-EfficientDet-Pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\PycharmProjects\pytorch-YOLOv4\dataset.py", line 274, in __getitem__
    img_path = os.path.join(self.cfg.dataset_dir, img_path)
AttributeError: 'EasyDict' object has no attribute 'dataset_dir'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
查看了一下cfg.py文件，发现在文件中的确没有”dataset_dir”这一项

# -*- coding: utf-8 -*-
'''
@Time          : 2020/05/06 21:05
@Author        : Tianxiaomo
@File          : Cfg.py
@Noice         :
@Modificattion :
    @Author    :
    @Time      :
    @Detail    :

'''
import os
from easydict import EasyDict


_BASE_DIR = os.path.dirname(os.path.abspath(__file__))

Cfg = EasyDict()

Cfg.use_darknet_cfg = True
Cfg.cfgfile = os.path.join(_BASE_DIR, 'cfg', 'yolov4.cfg')

Cfg.batch = 4
Cfg.subdivisions = 1
Cfg.width = 608
Cfg.height = 608
Cfg.channels = 3
Cfg.momentum = 0.949
Cfg.decay = 0.0005
Cfg.angle = 0
Cfg.saturation = 1.5
Cfg.exposure = 1.5
Cfg.hue = .1

Cfg.learning_rate = 0.00261
Cfg.burn_in = 1000
Cfg.max_batches = 500500
Cfg.steps = [400000, 450000]
Cfg.policy = Cfg.steps
Cfg.scales = .1, .1

Cfg.cutmix = 0
Cfg.mosaic = 1

Cfg.letter_box = 0
Cfg.jitter = 0.2
Cfg.classes = 1
Cfg.track = 0
Cfg.w = Cfg.width
Cfg.h = Cfg.height
Cfg.flip = 1
Cfg.blur = 0
Cfg.gaussian = 0
Cfg.boxes = 60  # box num
Cfg.TRAIN_EPOCHS = 300
Cfg.train_label = os.path.join(_BASE_DIR, 'E:/PycharmProjects/pytorch-YOLOv4/data/', 'train.txt')
Cfg.val_label = os.path.join(_BASE_DIR, 'E:/PycharmProjects/pytorch-YOLOv4/data/', 'val.txt')
# Cfg.train_label = os.path.join('E:/PycharmProjects/pytorch-YOLOv4/data/', 'train.txt')
# Cfg.val_label = os.path.join('E:/PycharmProjects/pytorch-YOLOv4/data/', 'val.txt')
Cfg.TRAIN_OPTIMIZER = 'adam'
'''
image_path1 x1,y1,x2,y2,id x1,y1,x2,y2,id x1,y1,x2,y2,id ...
image_path2 x1,y1,x2,y2,id x1,y1,x2,y2,id x1,y1,x2,y2,id ...
...
'''

if Cfg.mosaic and Cfg.cutmix:
    Cfg.mixup = 4
elif Cfg.cutmix:
    Cfg.mixup = 2
elif Cfg.mosaic:
    Cfg.mixup = 3

Cfg.checkpoints = os.path.join(_BASE_DIR, 'checkpoints')
Cfg.TRAIN_TENSORBOARD_DIR = os.path.join(_BASE_DIR, 'log')

Cfg.iou_type = 'iou'  # 'giou', 'diou', 'ciou'

Cfg.keep_checkpoint_max = 10

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
但是在datasets.py文件中，最后部分又有了这一个配置项
if __name__ == "__main__":
    from cfg import Cfg
    import matplotlib.pyplot as plt

    random.seed(2020)
    np.random.seed(2020)
    Cfg.dataset_dir = '/mnt/e/Dataset'
    dataset = Yolo_dataset(Cfg.train_label, Cfg)
    for i in range(100):
        out_img, out_bboxes = dataset.__getitem__(i)
        a = draw_box(out_img.copy(), out_bboxes.astype(np.int32))
        plt.imshow(a.astype(np.int32))
        plt.show()

**Comment by xwq-jfl** [comment]
这个dir是命令行输入的，其实如果你cfg里配置好了都不用弄，dataset底下那个是不会运行到那里的，不影响

**Comment by jaguarzhang** [comment]
> img_path = self.imgs[index]
> bboxes = np.array(self.truth.get(img_path), dtype=np.float) # bboxes = [[x1,y1,x2,y2,c],...]
> #img_path = os.path.join(self.cfg.dataset_dir, img_path)
> 如果img_path = self.imgs[index]可以得到图片的绝对路径，就不需要最后一句了。如果得到的是相对路径，需要加上这句变为图片的绝对路径img_path = os.path.join(self.cfg.dataset_dir, img_path) 。可以去看一下train2017.txt里面图片的路径。

谢谢，我是在Windows系统上运行的 ，所以可能会有一点差异
