### ISSUE TITLE
label 路径在哪里啊？

### ISSUE THREAD

**Issue by Jackerho** [Tianxiaomo/pytorch-YOLOv4#294]
train_dataset = Yolo_dataset(config.train_label, config, train=True)
    val_dataset = Yolo_dataset(config.val_label, config, train=False)

运行train.py

log file path:log\log_2020-10-13_20-38-09.txt
2020-10-13 20:38:10,358 train.py[line:611] INFO: Using device cpu
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
Traceback (most recent call last):
  File "D:/Project/python/pytorch-YOLOv4-master/train.py", line 626, in <module>
    device=device, )
  File "D:/Project/python/pytorch-YOLOv4-master/train.py", line 292, in train
    train_dataset = Yolo_dataset(config.train_label, config, train=True)
  File "D:\Project\python\pytorch-YOLOv4-master\dataset.py", line 255, in __init__
    f = open(label_path, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'train.txt'

**Comment by Jackerho** [comment]
Cfg.train_label = os.path.join(_BASE_DIR, 'data', 'train.txt')
Cfg.val_label = os.path.join(_BASE_DIR, 'data', 'val_label.txt')
路径没问题，但还是找不到train.txt

**Comment by ws1414153477** [comment]
train.txt放到主路径就可以了

**Comment by Jackerho** [comment]
> train.txt放到主路径就可以了

谢谢，可以运行，不过还是保守点好

**Comment by THEBEST-cloud** [comment]
请问是放在data目录下吗，为什么我放在data目录下也没有用呢

**Comment by Whynot-me** [comment]
标签中的坐标值需要归一化吗

**Comment by THEBEST-cloud** [comment]
需要的
---原始邮件---
发件人:&quot;Whynot-me&quot;<notifications@github.com&gt;
发送时间:2020年11月5日 星期四 下午7:5
收件人:&quot;Tianxiaomo/pytorch-YOLOv4&quot;<pytorch-YOLOv4@noreply.github.com&gt;
抄送:&quot;THEBEST-cloud&quot;<1543012632@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [Tianxiaomo/pytorch-YOLOv4] label 路径在哪里啊？ (#294)



标签中的坐标值需要归一化吗

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by ynzzxc** [comment]
修改train.py第544行默认路径或者在训练命令中指定路径
parser.add_argument('-train_label_path', dest='train_label', type=str, default='train.txt', help="train label path")
