### ISSUE TITLE
请问val.txt该怎么设置？

### ISSUE THREAD

**Issue by EternalEvan** [Tianxiaomo/pytorch-YOLOv4#303]
在仿照作者训练的时候出现了以下错误：
 python train.py -l 0.001 -g 1 -pretrained ./yolov4.conv.137.pth -classes 3
coins/coinspython train.py -l 0.001 -g 1 -pretrained ./yolov4.conv.137.pth -classes 3
-dir coins/coinslog file path:log/log_2020-10-21_00-13-30.txt
2020-10-21 00:13:30,273 train.py[line:611] INFO: Using device cuda
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
Traceback (most recent call last):
  File "train.py", line 626, in <module>
    device=device, )
  File "train.py", line 293, in train
    val_dataset = Yolo_dataset(config.val_label, config, train=False)
  File "/home/XXX/pytorch-YOLOv4/dataset.py", line 256, in __init__
    f = open(lable_path, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/XXX/pytorch-YOLOv4/data/val.txt'

求求老哥指点应该怎么设置val.txt呀？

**Comment by EternalEvan** [comment]
就是use yolov4 to train your own data.md里面用硬币训练的时候

**Comment by neoragex2002** [comment]
自己设置、改写下train.py和cfg.py，``Cfg.val_label``, 里面的配置设置代码一塌糊涂...

**Comment by Bruce-Si** [comment]
同问，val.txt该怎么设置啊？

**Comment by 705062791** [comment]
val.txt 是测试训练集合，格式和train.txt一致，在训练的时候不需要val.txt, 把那段代码注释掉就可以了．作者的代码写的很乱，测试和训练过程没有分开．
