### ISSUE TITLE
convert yolov3-tiny to onnx

### ISSUE THREAD

**Issue by nazzzaroff** [Tianxiaomo/pytorch-YOLOv4#313]
Can I convert yolov3-tiny to onnx?
When I run darknet2onnx.py with my cfg and weights, I get an error:
```python
convalution havn't activate linear
Traceback (most recent call last):
  File "darknet2onnx.py", line 59, in <module>
    transform_to_onnx(cfgfile, weightfile)
  File "darknet2onnx.py", line 8, in transform_to_onnx
    model = Darknet(cfgfile)
  File "/home/alex/work/repos/pytorch-YOLOv4/tool/darknet2pytorch.py", line 140, in __init__
    self.models = self.create_network(self.blocks)  # merge conv, bn,leaky
  File "/home/alex/work/repos/pytorch-YOLOv4/tool/darknet2pytorch.py", line 405, in create_network
    yolo_layer.scale_x_y = float(block['scale_x_y'])
KeyError: 'scale_x_y'
```

**Comment by lswgh** [comment]
same problem! have you soled the error?
THANKS!

**Comment by ROBYER1** [comment]
Same here, lack of v3 tiny support is an issue

**Comment by bainro** [comment]
Add "scale_x_y = 1.00" to each [yolo] layer in the cfg file. This is implicit for yolov3, but the parser doesn't know that currently. 

https://github.com/ultralytics/yolov3/issues/1121
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-tiny-3l.cfg
