### ISSUE TITLE
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by azhar-autocanvas** [Tianxiaomo/pytorch-YOLOv4#333]
I get following error when first training epoch is complete.

Epoch 1/300: 100%|▉| 1124/1126 [02:00<00:00,  9.92convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
in function convert_to_coco_api...
creating index...
index created!
Epoch 1/300: 100%|▉| 1124/1126 [02:03<00:00,  9.08
Traceback (most recent call last):
  File "train.py", line 630, in <module>
    device=device, )
  File "train.py", line 429, in train
    evaluator = evaluate(eval_model, val_loader, config, device)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "train.py", line 489, in evaluate
    outputs = model(model_input)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Autocanvas/b5d2a468-e99c-44e9-8e2d-3b2c6b4cbd87/Home/Azhar/traffic_sign_detection/models/pytorch-YOLOv4/tool/darknet2pytorch.py", line 161, in forward
    x = self.models[ind](x)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Autocanvas/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by LIUhansen** [comment]
Do u solve this?

**Comment by xlq57913** [comment]
I change the line485 in train.py to **outputs = model(model_input.float())** to avoid the problem
