### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by ZongDaa** [Tianxiaomo/pytorch-YOLOv4#383]
Epoch 1/300:   0%|      | 0/5000 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/home/xxxy01/502/zd/pytorch-YOLOv4-master/train.py", line 626, in <module>
    device=device, )
  File "/home/xxxy01/502/zd/pytorch-YOLOv4-master/train.py", line 370, in train
    for i, batch in enumerate(train_loader):
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xxxy01/502/zd/pytorch-YOLOv4-master/dataset.py", line 352, in __getitem__
    sheight, self.cfg.w, self.cfg.h)
  File "/home/xxxy01/502/zd/pytorch-YOLOv4-master/dataset.py", line 79, in fill_truth_detection
    min_w_h = np.array([bboxes[:, 2] - bboxes[:, 0], bboxes[:, 3] - bboxes[:, 1]]).min()
  File "/home/xxxy01/anaconda2/envs/zd/lib/python3.6/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by bigTLMN** [comment]
Did you solve it? I meet this problem too

**Comment by bigTLMN** [comment]
@ZongDaa  Did you solve it? I meet this problem too

**Comment by Qianrj0735** [comment]
I met this problem and solved it out by giving the train.py a correct class number
