### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package

### ISSUE THREAD

**Issue by undefined0x0** [Tianxiaomo/pytorch-YOLOv4#398]
Hi, 

Any ideas?

Thx!
```
Converting to onnx and running demo ...
Traceback (most recent call last):
  File "demo_pytorch2onnx.py", line 96, in <module>
    main(weight_file, image_path, batch_size, n_classes, IN_IMAGE_H, IN_IMAGE_W)
  File "demo_pytorch2onnx.py", line 72, in main
    transform_to_onnx(weight_file, batch_size, n_classes, IN_IMAGE_H, IN_IMAGE_W)
  File "demo_pytorch2onnx.py", line 19, in transform_to_onnx
    pretrained_dict = torch.load(weight_file, map_location=torch.device('cuda'))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
**ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package**
```

**Comment by Anas-Alshaghouri** [comment]
Hello
Did you find a solution @undefined0x0 ?
I am facing same error.

**Comment by Mbincao** [comment]
I also met the problem,could you show me the solutions.

**Comment by Joker19920330** [comment]
I also met the problem,could you show me the solutions.
