### ISSUE TITLE
当我训练时会自动停止，报错如下

### ISSUE THREAD

**Issue by zh9369** [Tianxiaomo/pytorch-YOLOv4#45]
Traceback (most recent call last):
  File "train.py", line 429, in <module>
    device=device, )
  File "train.py", line 305, in train
    bboxes_pred = model(images)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorch-YOLOv4-master/models.py", line 417, in forward
    d3 = self.down3(d2)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorch-YOLOv4-master/models.py", line 173, in forward
    x1 = self.conv1(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorch-YOLOv4-master/models.py", line 58, in forward
    x = l(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorch-YOLOv4-master/models.py", line 10, in forward
    x = x * (torch.tanh(torch.nn.functional.softplus(x)))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4647) is killed by signal: Killed. 

我的cuda版本为10.2，显存9G，设置num_works=1，还是会自己中断？

**Comment by Tianxiaomo** [comment]
设置为0试试

**Comment by zh9369** [comment]
还是不行，自动关闭进程

**Comment by Tianxiaomo** [comment]
我用地是版本是1.4，你看看你的版本，如果还是error，我也不知道了

**Comment by zh9369** [comment]
我试了1.4的版本也不行，昨天好像还可以，今天突然就不行了，我再找找原因
