### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by Arvin1201** [Tianxiaomo/pytorch-YOLOv4#57]
/pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:57: UserWarning: Traceback of forward call that caused the error:
  File "/home/qw/github/ObjectDetect/pytorch-YOLOv4-master/train.py", line 453, in <module>
    device=device, )
  File "/home/qw/github/ObjectDetect/pytorch-YOLOv4-master/train.py", line 329, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "/home/qw/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qw/github/ObjectDetect/pytorch-YOLOv4-master/train.py", line 210, in forward
    output[..., np.r_[0:4, 5:n_ch]] *= tgt_mask

Epoch 1/500:   0%|       | 0/103 [00:05<?, ?img/s]
Traceback (most recent call last):
  File "/home/qw/github/ObjectDetect/pytorch-YOLOv4-master/train.py", line 453, in <module>
    device=device, )
  File "/home/qw/github/ObjectDetect/pytorch-YOLOv4-master/train.py", line 331, in train
    loss.backward()
  File "/home/qw/.local/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/qw/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 3, 19, 19, 7]], which is output 0 of torch::autograd::CopySlices, is at version 7; expected version 4 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Tianxiaomo** [comment]
看一下pytorch版本，我记得issuses有人提过这个问题

**Comment by Arvin1201** [comment]
好的   升级pytorch版本就解决了

**Comment by Sukeysun** [comment]
除了升级版本，也可以重写一下 train.py里的Yolo_loss。出现这个原因可能是预测出的boxes_pred在Yolo_loss里被修改了，用来计算loss的boxes_pred的是一个值，计算loss之后boxes_pred又是另外一个值， torch反向更新的时候就会出错。可以在计算loss的时候，创建一个跟boxes_pred相同尺寸的新的变量，将对boxes_pred的改动赋给这个新的变量。根据新变量里的值计算loss, 最后把新变量和loss一起作为输出。
