### ISSUE TITLE
训练size为416时报错

### ISSUE THREAD

**Issue by myl353** [Tianxiaomo/pytorch-YOLOv4#83]
您好，我将输入大小改为416后，出现报错：
Traceback (most recent call last):
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/train_mine.py", line 457, in <module>
    device=device, )
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/train_mine.py", line 324, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/train_mine.py", line 205, in forward
    pred[..., 0] += self.grid_x[output_id]
RuntimeError: The size of tensor a (52) must match the size of tensor b (76) at non-singleton dimension 3

改为608后又可以训练，请问是哪里没有调整正确呢？

**Comment by Dylanbron** [comment]
请问您修改输入大小，训练成功了吗

**Comment by Dylanbron** [comment]
你这应该是改成长宽不相等了吧，这个代码里面计算Yolo Loss长宽必须相等

**Comment by myl353** [comment]
成功了，它是后面代码有一块写死了，需要修改



---原始邮件---
发件人: "shenyq"<notifications@github.com&gt;
发送时间: 2020年6月8日(周一) 中午1:38
收件人: "Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;;
抄送: "myl353"<980477635@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Tianxiaomo/pytorch-YOLOv4] 训练size为416时报错 (#83)




 
请问您修改输入大小，训练成功了吗

**Comment by KelvinHuang666** [comment]
@myl353 可以贴一下您的代码让我学习学习？？

**Comment by myl353** [comment]
在train.py的93行，有一个image_size



---原始邮件---
发件人: "KelvinHuang666"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 中午11:28
收件人: "Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"myl353"<980477635@qq.com&gt;;
主题: Re: [Tianxiaomo/pytorch-YOLOv4] 训练size为416时报错 (#83)




 
@myl353 可以贴一下您的代码让我学习学习？？

**Comment by mon28** [comment]
Thanks @myl353! What would i do if google translate didn't exist!?!
