### ISSUE TITLE
darknet2onnx 报错：RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 4598739

### ISSUE THREAD

**Issue by myl353** [Tianxiaomo/pytorch-YOLOv4#84]
您好，我训练完自己的数据集后，在转为onnx时报错：
Traceback (most recent call last):
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/fwq/soft/pycharm-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/tool/darknet2onnx.py", line 41, in <module>
    fransform_to_onnx(cfgfile, weightfile)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/tool/darknet2onnx.py", line 10, in fransform_to_onnx
    model.load_weights(weightfile)
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/tool/darknet2pytorch.py", line 402, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "/e/myl/yolov4_study/pytorch_YOLOv4_Tianxiaomo/tool/config.py", line 224, in load_conv_bn
    def save_conv_bn(fp, conv_model, bn_model):
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 4598739

在训练期间，我只修改了输入大小和类别数，其它完全没有进行修改，对cfg中的输入和clases也进行了对应的修改，可是在转onnx时，报出这个错误，请问需要怎么修改？》？

**Comment by myl353** [comment]
@Tianxiaomo models.py的Yolov4和darknet2pytorch.py的Darknet 模型不一致，导致了darknet2onnx是错误，请问有什么修改方法呢？、

**Comment by ersheng-ai** [comment]
You can update the darknet cfg file's input size to keep shapes consistent.
```sh
[net]
batch=64
subdivisions=8

# Training
#width=608
#height=608

width=608
height=608

#width=416
#height=416

#width=512
#height=512

#width=320
#height=320
```

**Comment by zhangyuge10** [comment]
@myl353,in yolov4.cfg,before yolo ,filters change (5+class)*3
