### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by gangooteli** [Tianxiaomo/pytorch-YOLOv4#96]
python train.py -l 0.001 -classes 2 -g '0' -dir ../Yet-Another-EfficientDet-Pytorch/datasets/shape/train/
log file path:log/log_2020-06-08_00-59-06.txt
2020-06-08 00:59:06,724 train.py[line:433] INFO: Using device cuda
2020-06-08 00:59:07,975 train.py[line:282] INFO: Starting training:
        Epochs:          300
        Batch size:      1
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   900
        Validation size: 100
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 2
        Train label path:train.txt
        Pretrained:
    
Epoch 1/300:   0%|       | 0/900 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 445, in <module>
    device=device, )
  File "train.py", line 319, in train
    bboxes_pred = model(images)
  File "/home/nikhil/anaconda/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nikhil/ScratchDetection/Project/pytorch-YOLOv4/models.py", line 410, in forward
    d1 = self.down1(input)
  File "/home/nikhil/anaconda/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nikhil/ScratchDetection/Project/pytorch-YOLOv4/models.py", line 107, in forward
    x1 = self.conv1(input)
  File "/home/nikhil/anaconda/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nikhil/ScratchDetection/Project/pytorch-YOLOv4/models.py", line 51, in forward
    x = l(x)
  File "/home/nikhil/anaconda/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nikhil/anaconda/envs/torch1.4/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 98, in forward
    self.num_batches_tracked = self.num_batches_tracked + 1
RuntimeError: CUDA error: no kernel image is available for execution on the device

Getting above error. Not able to resolve after lot of trying.

**Comment by gangooteli** [comment]
Below are the more details.

torch                     1.4.0                     <pip>
torchvision               0.5.0                     <pip>


$nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105


| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |

I am using conda environment. Please help
